name: flutter_reddit_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # UI
  flutter_svg: ^1.1.6
  # Infrastructure
  flutter_bloc: ^8.1.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  get_it: ^7.2.0
  # http
  http: ^0.13.5
  # Remote API
  internet_connection_checker: ^1.0.0+1
  # ruteo
  auto_route: ^5.0.4

  cupertino_icons: ^1.0.2

dev_dependencies:
  build_runner: ^2.3.3
  auto_route_generator: ^5.0.3
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  flutter_lints: ^2.0.0
  # Flavors
  flutter_flavorizr: ^2.1.6
  
flavorizr: #flutter pub run flutter_flavorizr
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    dev:
      app:
        name: "Flutter Reddit Dev"

      android:
        applicationId: "com.example.flutter_reddit_app.dev"
      ios:
        bundleId: "com.example.flutter_reddit_app.dev"

    staging:
      app:
        name: "Flutter Reddit Staging"

      android:
        applicationId: "com.example.flutter_reddit_app.staging"
      ios:
        bundleId: "com.example.flutter_reddit_app.staging"

    production:
      app:
        name: "Flutter Reddit Prod"

      android:
        applicationId: "com.example.flutter_reddit_app.prod"
      ios:
        bundleId: "com.example.flutter_reddit_app.prod"
    

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/icons/app_bar/
  fonts:
    - family: PoppinsItalic
      fonts:
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 400
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          weight: 900
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900

